### ISSUE TITLE
Problem: still using github issue tracker

### ISSUE THREAD

**Issue by gazhayes** [nostrocket/spaceman#10]
Problem: still using github issue tracker

Solution: make nostrocket issue tracker useable

- [x] can log problems
- [x] can edit problems
- [ ] can claim problems
  - [x] can request to join identity tree
  - [x] existing identity tree plebs can approve new ones
- [ ] event tree updated to use mainnet
